### ISSUE TITLE
Validate signatures for votes received from peers

### ISSUE THREAD

**Issue by adoerr** [paritytech/grandpa-bridge-gadget#100]
`BeefyWorker::handle_vote()` should validate vote signatures before processing them.

**Comment by andresilva** [comment]
#142 implemented verification of the signatures but we still need to make sure the given signer is part of the validator set.

**Comment by adoerr** [comment]
Verify , that the `msg.id` in [this](https://github.com/paritytech/grandpa-bridge-gadget/blob/9be54d3e816d8e8e7aae392f70d5c6531ad00b26/beefy-gadget/src/worker.rs#L122) line is a member of the validator set.

**Comment by tomusdrw** [comment]
This could also be done in `Round` structure (`add_vote`) or earlier.
