### ISSUE TITLE
BEEFY equivocation processing

### ISSUE THREAD

**Issue by adoerr** [paritytech/grandpa-bridge-gadget#101]
BEEFY must deal with equivocations. That includes at least

- detect equivocations
- report equivocations
- initiate slashing

**Comment by tomusdrw** [comment]
Since BEEFY is based on GRANDPA, there is an edge case that Alistair recently mentioned:

> We can have BEEFY validators slashable for voting for something on a different fork when this one was finalised. This is not quite an equivocation, and we should cancel the slash if they can point out a valid GRANDPA justification for the fork they voted for.

**Comment by acatangiu** [comment]
Closing in favor of https://github.com/paritytech/substrate/issues/12692
