### ISSUE TITLE
Improve BEEFY rounds lifecycle.

### ISSUE THREAD

**Issue by adoerr** [paritytech/grandpa-bridge-gadget#102]
Currently BEEFY is just starting a new round according to the voting rule (next-power-of-two), regardless of how many previous rounds are still running. We should have a more defined round lifecycle with clear rules for when we start a new round (rather than running all in parallel wildly), and also what happens to old rounds in the face of new rounds being concluded.

Also see the related issue [Improve block-selection strategy](https://github.com/paritytech/grandpa-bridge-gadget/issues/16)

**Comment by tomusdrw** [comment]
BEEFY should only have one active voting round. More details will come in #320
