### ISSUE TITLE
Enact validator set change starting with the next round/block

### ISSUE THREAD

**Issue by adoerr** [paritytech/grandpa-bridge-gadget#103]
Right now, if the `validator_set_id` changes, we use this new set id for the signed commitment of the current round/block already. The new set id should be enacted starting with the next round/block, however.

This is related to [Improve BEEFY rounds livecycle](https://github.com/paritytech/grandpa-bridge-gadget/issues/102l)

**Comment by tomusdrw** [comment]
According to #320, when validator set is changed all previous rounds should be discarded, so it's fine to start a new round. Also related #183
