### ISSUE TITLE
Expose BEEFY prometheus metrics.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#119]
After a "production" deployment of BEEFY (for instance on Westend / Rococo) it will be really nice to collect some metrics and get some insight of what happens inside the BEEFY gadget / gossip.
I'd see what metrics we expose for GRANDPA and copy that, but what would be interesting from the top of my head:
1. Current Validator Set Id
2. Round state: starting / concluding
3. Number of valid signed commitments received per round (with required threshold information)
4. Number of incoming / outgoing gossip messages / commitments per round.

**Comment by adoerr** [comment]
Prometheus metric setup has been done with #125. Current validator set id is available as a metric as part of this PR as well.

Further metrics need a bit of a refinement, though. Exposing anything other than a simple numeric value is not really straightforward. So a metric is basically either a value or a counter.
