### ISSUE TITLE
Use bitfield in `SignedCommitment` for encoded-size optimisation.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#128]
Currently `SignedCommitment` uses `Vec<Option<Signature>>>` for the list of signatures. This vector is expected to contain at least 2/3+1 `Some` values anyway.

It's possible to optimize the storage though, and save 7 bits (1byte for enum variant vs 1 bit) per every signature in SCALE encoded form (minus alignment) by using a different scheme of:
```
signatures_from: BitField,
signatures: Vec<Signature>,
```
Every set bit in `signatures_from` signifies the index of validator that the next signature in `signatures` vec is for.

I think this should be implemented as custom SCALE encoding and we should keep the current `struct` format for backward compatibility (code not over-the-wire).

**Comment by de-sh** [comment]
Hey, I am interested in working on this. From my understanding, you are referring to [beefy-primitives::commitment.rs#L88](https://github.com/paritytech/grandpa-bridge-gadget/blob/master/beefy-primitives/src/commitment.rs#L88). I am not very familiar with the SCALE encoding, but would it be enough to skim through [documentation](https://substrate.dev/docs/en/knowledgebase/advanced/codec)?

Please let me know if there is any forum I should use to clear my confusions, happy to contribute in any way possible.

**Comment by acatangiu** [comment]
@tomusdrw is there anything left to do here, or can we close it on account of https://github.com/paritytech/substrate/pull/10409?

**Comment by tomusdrw** [comment]
It's done, thanks!
