### ISSUE TITLE
Merkle root of signatures is not needed in the interactive protocol

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#13]
It seems that providing a merkle root of signatures in the interactive protocol doesn't really add any value, Alistair proposed a different scheme where we just provide one signature + public key with the commitment, details to follow.

**Comment by AlistairStewart** [comment]
Well the trade off is not so clear. What is clear is that dropping the Merkle root of signatures  saves between 1/3-1/2 of the data size of an interactive proof on Ethereum, which will save signifiacantly on the gas cost.

The downsides are two: 

1) It means that validators could in theory be bribed after being chosen and only sign then.
2) It means that relayers could claim a block without having all the signatures they claim in an effort to be first.

For 2, I think we will have a deposit behind the first transaction, which should discourage this. 1 is only a problem if 2/3 of validators are running hacked software. Even with a Merkle tree of signatures, they could build the Merkle tree of signatures on the bad block, and would only have to share their bad signature with maybe one other validator, the guy whose signature they need to hash together to get the next Merkle tree node up from the leaves.

These seem like theoretical problems compared to the very real gas cost problem. @burdges

**Comment by tomusdrw** [comment]
Closing, since I have the interactive protocol is a bit changed now and it isn't really implemented in this repo.
