### ISSUE TITLE
Custom RPC for BEEFY Justifications

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#18]
Similar to GRANDPA RPC, should support:
- onDemand retrieval - get the `SignedCommitment` from DB (see #17) if there is any
- subscription - receive `SignedCommitments` as soon as they are available

**Comment by andresilva** [comment]
#26 implements the subscription API.

**Comment by tomusdrw** [comment]
Implemented. Persisted signed commitments can be retrieved from `chain_getBlock` RPC, they are part of justifications vector.
