### ISSUE TITLE
BEEFY-specific `import_justification`

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#183]
Since now BEEFY `SignedCommitments` are part of block justfications now (#177) we should plug into `import_justification` client stuff so that we can update the Worker state when signed commitments are being imported (for instance to track the validator set hand-offs).

**Comment by acatangiu** [comment]
We want to add dedicated substrate protocol for this instead of using block-import or sync. Will come back with more details when we settle on a design.

**Comment by acatangiu** [comment]
Closing, also tracked by https://github.com/paritytech/grandpa-bridge-gadget/issues/20
