### ISSUE TITLE
BEEFY sync protocol

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#20]
Currently the node has to be on-line to receive and store BEEFY justifications. If it falls behind it can rely on syncing the justification data along with the blocks (see #17), but there is no guarantee that we will get all of them (depends on who do we sync from).

Syncing only BEEFY justifications is also useful for Super Light Clients (see https://github.com/paritytech/parity-bridges-common/issues/323 - beyond Solidity) - we could for instance sync Substrate Connect with this (see also https://github.com/paritytech/substrate/issues/1208).

We should probably introduce:
- [ ] BEEFY justification gossip
- [ ] Sync protocol only for essential BEEFY justifications (session change blocks, era change blocks).

**Comment by seunlanlege** [comment]
Would love to use this to get to understand substrates networking protocol better. Is there mentorship available for this task?

**Comment by tomusdrw** [comment]
Details will be outlined in #320 soonish.
Related #183

**Comment by acatangiu** [comment]
We want to add dedicated substrate protocol for this instead of using block-import or sync. Will come back with more details when we settle on a design.

**Comment by acatangiu** [comment]
Closing here, tracking issue in https://github.com/paritytech/substrate/issues/12093
