### ISSUE TITLE
ParachainHeads & BEEFY validators in MMR are incorrect

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#221]
Currently we make a **trie** (modifier base-16 patricia-merkle tree) out of parachain heads and BEEFY validators uncompressed public keys.

It is quite redundant though and not that easy to verify in Solidity.

Instead we should make a regular binary tree out of:
1. `(para_id, para_head)` (to make it easy to figure out which parachain is which)
2. `ethereum addresses` of BEEFY validators (afair: `address = keccak256(uncompressed_public_key)[0..20]`; to make it faster to verify on ETH)

Note that there are no host functions to compute the binary tree root, so we should either consider adding them (cumbersome!) or check if in-runtime implementation is feasible (I'd start from the latter and only optimize as a host function after).

**Comment by tomusdrw** [comment]
Implemented already.

**Comment by AurevoirXavier** [comment]
How about using sparse-merkle-tree?
It will be much easier to verify multiple leaves. And the tree won't be too large in this case.

**Comment by tomusdrw** [comment]
Can you elaborate? What would be the domain of leaves? What advantage you are striving for?

In case of parachains we could potentially use the id, but the tree may still end up being quite large, because afair the parachain ids can be picked arbitrarily. In case of BEEFY validators we are speaking of 2^160 possible leaves, we would need to bring this down obviously, but I don't see much advantage over just regular merkle tree, especially given that a sparse one (if we put addresses into some buckets) becomes attackable, since validators can pick addresses arbitrarily.

**Comment by hujw77** [comment]
If we have 5 BEEFY validators.
For regular binary tree.
```
                      1
          2                       3'
    4'          5                 3
  6    7     8'    9*             3
  A    B     C     D              E
```
For leaf D, 
witness:  `8, 4, 3`
prove: `H(H(4, H(8,9)), 3) == 1`  
This is an efficient way for one leaf inclusion proof.

But if we extend the leaf to be a sparse merkle tree, 
```
                      1
          2                       3
    4'          5           6           7'
  8    9     10*  11*    12*  13'    14   15
  A    B     C     D     E    Ø      Ø    Ø
```
It will be very easy for a multi-leave proof.
For leaves C, D and E
witness:  `4, 13, 7` 
prove: `H(H(4, H(10,11)), H(H(12,13), 7)) == 1`  

For regular binary tree, it also support multi-leaves too, but the indices is not friendly for verify in solidity.
more detail can see https://github.com/Snowfork/snowbridge/pull/555

**Comment by tomusdrw** [comment]
I see, thanks for the explanations!

So for a regular tree, it's still possible to prove multiple leaves, for `C, D, E` from your first example the witness data is just: `4', but we need to know the indices.

AFAIU, the idea you propose is to extend the number of leaves to the closest power of two, so that we get a full binary tree. The missing leaves are filled with some sort of `0/null` values. And the trade-off is to have simpler multi-leaf verification algorithm but perform a little bit more hashing in an average use case (`H(..., 7)==3` in the above example is completely redundant, but potentially could be optimised by avoiding hashing in case one of the operands is `0/null`, which starts to look surprisingly similar to the regular tree we have in example 1). 

TBH I don't fully understand where the actual optimisation/simplification is, but I probably haven't look deep enough in the implementation.
I think it would be great to see the concrete numbers comparing both approaches (the Snowbridge is taking even simpler approach of providing multiple proofs, but obviously that's going to be costly) and how much the Solidity code simplifies.

**Comment by hujw77** [comment]
There is the benchmark for single-leaf merkle proof and multi-leave proof: https://github.com/darwinia-network/darwinia-bridge-sol/pull/104#issuecomment-992191896
`10W Gas saving`
I think the Snowbridge will have the same good benchmark result by using the sparse merkle tree multi-proof.
