### ISSUE TITLE
Noting Rounds broken for non-authorities

### ISSUE THREAD

**Issue by adoerr** [paritytech/grandpa-bridge-gadget#237]
The current implementation for noting rounds is broken for non-authorities, i.e. non-validators and validators without a local authority id.

Root cause is that `ConsensusGossip` discards the vote message [here](https://github.com/paritytech/substrate/blob/993907f9deb180795b291ba752b9c204165d74dc/client/network-gossip/src/state_machine.rs#L376) because of [this](https://github.com/paritytech/grandpa-bridge-gadget/blob/bb28906d34db18140bdd8b94875f755e6970a174/beefy-gadget/src/gossip.rs#L139) before a non authority node even sees the message. In other words, vote messages are never effectively delivered to non authority nodes.

Basically we have a Catch-22 like situation for noting rounds regarding non authority nodes. Rounds are noted in [handle_vote()](https://github.com/paritytech/grandpa-bridge-gadget/blob/bb28906d34db18140bdd8b94875f755e6970a174/beefy-gadget/src/worker.rs#L302). However, this function will never be called, if the vote message never gets delivered (because it got discarded) in the first place.

The screenshot attached illustrates this. For the test run the `GossipValidtor::validate()` function has been instrumented to emit a debug trace when an unknown (`!is_live()`) gossip message gets discarded.

![Screenshot from 2021-07-14 06-33-45](https://user-images.githubusercontent.com/8516358/125561703-feddc1ae-9261-44d0-8412-8221591fad33.png)

One possible **preliminary** fix would be to use a [LruCache](https://docs.rs/lru/0.6.5/lru/index.html) of `MAX_LIVE_GOSSIP_ROUNDS`. This would make removal of vote messages for stale rounds automatic and we could note more liberally. At the same time we would only add a vote message for a new round, if the round number is greater than the round number of largest of the `MAX_LIVE_GOSSIP_ROUNDS` most recently used messages. Note that `LruCache` could be used with a hash builder.

In general, however, the whole peer management and with that the rounds life cycle needs to be reworked.

**Comment by andresilva** [comment]
`fn is_live(round) { known_rounds.contains(round) || round > known_rounds.max() }`. This is harder to implement now since known rounds was changed to be a hashset, it used to be a sorted vec.

**Comment by tomusdrw** [comment]
Rounds are in `BTreeMap`, we can still easily figure out the max and min.
