### ISSUE TITLE
BEEFY protocol name should change in accordance to GRANDPA protocol name

### ISSUE THREAD

**Issue by adoerr** [paritytech/grandpa-bridge-gadget#240]
The reasons outlined in [Change the name of the GrandPa notifications protocol](https://github.com/paritytech/substrate/issues/7252) are valid for `BEEFY` as well.

Hence, the `BEEFY` notification protocol name should be changed in accordance with the `GRANDPA` notification protocol name.

**Comment by tomusdrw** [comment]
I'd suggest to do that ASAP and merge along with #186 so that we can restart Rococo :)

**Comment by adoerr** [comment]
We can change the protocol ID from `paritytch` to `dot` for now. 

I'm hesitant to make the protocol ID configurable more or less unrestricted right now.  For example by introducing a `protocol_id` parameter to [beefy_peers_set_config()](https://github.com/paritytech/grandpa-bridge-gadget/blob/6c99d14caac1f9d9bad459b725b6ce6619cd34ee/beefy-gadget/src/lib.rs#L43-L49). If the `protocol_id` argument gets screwed up or is a duplicate or is just wrong, some pretty bad mayhem may be the result.

Ideally, once we have a more generic, configurable `BEEFY`, the `protocol_id` should become part of the set of accepted (and properly restricted) configuration values.

**Comment by adoerr** [comment]
Protocol Id's for the various chains can the found in the Polkadot chainspec [folder](https://github.com/paritytech/polkadot/tree/master/node/service/res)

**Comment by acatangiu** [comment]
Fixed in https://github.com/paritytech/substrate/pull/10463
