### ISSUE TITLE
Verify MMRLeaf version

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#255]
Currently the `decode-leaf` subcommand will happily decode every MMRLeaf - instead we should make sure to trigger a warning if the decode version does not match the expected one to avoid decoding BS.

**Comment by acatangiu** [comment]
What should be _the expected_ leaf version? I see the leaf version is defined by each chain runtime.
Whereas the `decode-leaf` subcommand of `beefy-cli` can be run against multiple chains (so potentially multiple leaf versions), right?

Should the `decode-leaf` subcommand take a parameter for _compatible major version number_ or something similar?

**Comment by tomusdrw** [comment]
The whole CLI is rather build around Polkadot's use case, so it should be matching whatever MMRLeaf version there is in Polkadot runtime.
