### ISSUE TITLE
Latest BEEFY-finalized block RPC

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#279]
We should return latest BEEFY-finalized block on-demand from the RPC.

The challenging part here is to always figure out what the current last finalized block is. While we have this info in memory in the worker, it might not be available initially.

To implement that properly we will need to plug into the import queue, and keep track of imported blocks especially during major sync.

As a temporary workaround we can just store the last finalized block from the worker perspective in AUX DB - this might get out of date during major sync, but I think it's going to be a minor inconvenience for now.

**Comment by tomusdrw** [comment]
Ideally substrate (`Client`) would expose an API to query the best block which contains justification `X`, os that we know where to start from.

**Comment by acatangiu** [comment]
Fixed in https://github.com/paritytech/substrate/pull/10568
