### ISSUE TITLE
Remove parachains mentions from Substrate repository

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#298]
Re: https://github.com/paritytech/substrate/pull/9833#discussion_r713735101

The `beefy-mmr` pallet contains now functions and fields specific to parachains, hence it does not necessarily fit Substrate repository.

IMHO the best way forward with this would be to generalize parachains to something like "leaf extra data". This extra data would have it's own `Provider` passed in `Config`. The data returned by `Provider` can have two flavors:
1. A single blob - include as is.
2. A collection - merkelize and include hash in the leaf.

**Comment by seunlanlege** [comment]
This makes sense, we could just call it `extras` and have it be a simple blob of bytes?

**Comment by tomusdrw** [comment]
I think `beefy-mmr` should probably be moved to polkadot repository since it contains payload that is specific to polkadot. I'd also suggest to extract `primitives` that are `beefy-mmr/polkadot` specific, like concrete `MmrLeaf`.

**Comment by acatangiu** [comment]
Fixed by https://github.com/paritytech/substrate/pull/10664 and https://github.com/paritytech/polkadot/pull/4719.
