### ISSUE TITLE
Update `on_initialize` weight calculations

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#351]
Follow up on #64 

After https://github.com/paritytech/substrate/pull/9700 was merged, the `on_initialize` weight calculation was not updated to accommodate for extra pruning reads/writes that are happening. It's probably safe to overestimate that and just add (doubled?) number of peaks as both reads and writes.

**Comment by acatangiu** [comment]
Looking at the pruning vs non-pruning storage `append` functions I think we don't need to update weight calculations, worst case `reads + writes` stays the same.

When adding new node results in pruning we are doing _extra_ pruning writes, but at the same time we're _no longer writing/saving_ their siblings to storage; with pruning we're only saving the new peak.

A simplified mental model is:
- without pruning: insert new nodes (right subtree) + insert parent -> n+1 writes
- with pruning: remove old peeks (left subtrees) + insert parent/peek -> n+1 writes

Number of reads of `max(peaks_before, peaks_after)` also looks correct.

I'm closing this issue, please reopen if you spot errors in above logic.
