### ISSUE TITLE
Merkle Mountain Belt implementation

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#353]
MMB is an alternative data structure to Merkle Mountain Range. The rationale to use MMB is to make the proofs of recently added items always small (in MMR they are sometimes small (i.e. few items), but every power-of-two leaves they might be as big as `log_2 n`).

Details can be requested from Alistair and Alfonso from Web3 Foundation.

Related #198

**Comment by acatangiu** [comment]
moved to https://github.com/paritytech/parity-bridges-common/issues/2463
