### ISSUE TITLE
Stalled BEEFY report

### ISSUE THREAD

**Issue by svyatonik** [paritytech/grandpa-bridge-gadget#377]
After adding BEEFY to [`Rialto test deployments`](https://github.com/paritytech/parity-bridges-common/tree/master/deployments) recently, we've observed BEEFY stall (just after deployments were restarted), with some interesting logs. I can easily repeat the same logs locally (by running scripts from https://github.com/svyatonik/parity-bridges-common.test), but has never seen yet stalled BEEFY there. Logs are:
```
...
gossip: Registering peer who=<PEER1> protocol=/paritytech/grandpa/1 role=Authority
gossip: Registering peer who=<PEER1> protocol=/paritytech/beefy/1 role=Authority
...
gossip: Registering peer who=<PEER2> protocol=/paritytech/grandpa/1 role=Authority
...
beefy: for block 9 public key missing in validator set: XXX
...
beefy: Missing validator id - can't vote for: YYY
```

So it seems that
1) nodes are sometimes fail to open "/paritytech/beefy/1" connection (see above - `PEER1` has registered two protocols and `PEER2` has only registered one). To me it seems like some race at networking level - need to explore lower-level logs;
2) `<missing>` things are strange, but they are  `DEBUG` logs, so probably not an error.

**Comment by acatangiu** [comment]
I believe this is fixed in https://github.com/paritytech/substrate/pull/10882
