### ISSUE TITLE
Use ABI Encoding for BEEFY?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/grandpa-bridge-gadget#394]
> https://github.com/paritytech/substrate/blob/master/client/beefy/src/worker.rs#L284-L290

BEEFY uses ECDSA to sign the message.
That's good.
And we can verify it easily on the Ethereum side.
But the commitment message is encoded through scale-codec.
That would cause a lot of extra gas costs.

Any idea on this?

**Comment by tomusdrw** [comment]
> That would cause a lot of extra gas costs.

Why is that? SCALE code is simply concatenation of binary data with known size (or with length prefix in case of Vec). Obviously if you want to build a generic SCALE encoder it's going to be expensive, but just encoding known types should be pretty optimized.

I don't think encoding BEEFY commitment using Ethereum-specific ABI format is a good idea. While BEEFY can be used for bridging with Ethereum it's not the only case and IMHO it's better avoid such tightly coupling.

Imagine we switch to ABI, after that any Substrate<>Substrate bridge would need to import EthABI decoder to be able to bridge with BEEFY.

Please also take a look how it's already solved in [Snowfork's Snowbridge implementation](https://github.com/Snowfork/snowbridge/blob/main/ethereum/contracts/BeefyLightClient.sol#L581) as an inspiration.

**Comment by hujw77** [comment]
@tomusdrw 
If encoding BEEFY commitment using scale codec, there is a [converting bytes (bid endian) to little endian format](https://github.com/Snowfork/snowbridge/blob/5f022159a61262bfcdc23db6c4d88b3393a961b1/ethereum/contracts/ScaleCodec.sol#L5). It's not friendly to Ethereum family chains.
I think If there is a custom codec fn for BEEFY commitment will be better.

**Comment by AurevoirXavier** [comment]
After a discussion, we think the scale-codec cost is acceptable.
