### ISSUE TITLE
Customize payload extraction

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#42]
Currently we extract the MMR root hash from the header digest, but long term it would be better to read the storage directly.
We need to do it right away, to prevent the state from being pruned by when GRANDPA finalises the block.

**Comment by seunlanlege** [comment]
This is the MMR root hash that we want to vote on?

**Comment by tomusdrw** [comment]
I think it would be best to start querying the MMR root hash (or payload in general) from the state as soon as possible and only add the digest item for Mandatory Blocks (see #320; i.e. the ones that contain the validator set change as as well) for potential future BEEFY header-aware light clients.

**Comment by tomusdrw** [comment]
Now with https://github.com/paritytech/grandpa-bridge-gadget/issues/198 implemented it should also be possible to customize the payload construction in the gadget code instead of having it hardcoded.

**Comment by acatangiu** [comment]
> Now with #198 implemented it should also be possible to customize the payload construction in the gadget code instead of having it hardcoded.

Split this to its own issue: https://github.com/paritytech/grandpa-bridge-gadget/issues/409

**Comment by acatangiu** [comment]
fixed in https://github.com/paritytech/substrate/pull/11183

MMR root is available both in header and state, currently worker tries from header, on failure falls back to state. In the future we can easily remove header digests and use state exclusively.
