### ISSUE TITLE
MMR non-peak nodes pruning

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#64]
It's still not implemented, and we need to do it before any production deployment.

**Comment by seunlanlege** [comment]
Would also love to take this on, mentorship available?

**Comment by adoerr** [comment]
This is kind of ongoing. Please see the [Support MMR Pruning](https://github.com/paritytech/substrate/pull/9700) PR.

**Comment by tomusdrw** [comment]
Closed via https://github.com/paritytech/substrate/pull/9700
