### ISSUE TITLE
Register BEEFY key type as a known key type

### ISSUE THREAD

**Issue by adoerr** [paritytech/grandpa-bridge-gadget#72]
Currently the BEEFY key type is defined in the `beefy-primitives` crate only. It has not been registered with the known key type registry in `sp_core::crypto::key_types`.

While this may not be strictly necessary from a technical point of view, it should still be done for the sake of consistency and completeness.

**Comment by adoerr** [comment]
Addressed with [Add BEEFY key type](https://github.com/paritytech/substrate/pull/8794)

**Comment by andresilva** [comment]
Not sure why you think we should add it to the substrate known key types if BEEFY is not there, whoever wants to use BEEFY will require `beefy-primitives`, so they can just fetch the key type from there. We also don't add the parachain-specific keys to the substrate known keys.

**Comment by tomusdrw** [comment]
Yeah, I think it is not needed. The keystore issue (#181) can be solved by introducing `ecdsa_sign_prehashed` method to `CryptoStore` trait.
