### ISSUE TITLE
BEEFY end-to-end test

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#81]
Currently we don't really have a proper integration test of BEEFY and the entire node (i.e. we don't know if it works; see #80)

It would be good to run a super high level integration test where:
1. We spawn two nodes (alice & bob)
2. We subscribe to BEEFY justifications
3. We wait for the first few justifications to be received and consider the test finished.

**Comment by acatangiu** [comment]
Done in https://github.com/paritytech/substrate/pull/10882
