### ISSUE TITLE
Allow hasher configuration before signing with app-crypto

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#82]
Substrate's `app-crypto` crate allows you to choose from different cryptography and generates application-specific `Public`, `Signature`, etc types.

In BEEFY we currently use `ECDSA` (over `secp256k1`) to make it the most compatible with Ethereum.

However, where we sign the `Commitment` (or rather the encoding of it) using [`SyncCryptoStore::sign_with` here](https://github.com/paritytech/grandpa-bridge-gadget/blob/9f4a049617ccc962c41b90f0b2c8c24c6380c2d4/beefy-gadget/src/lib.rs#L287), it would eventually end up [here](
https://github.com/paritytech/substrate/blob/07a5f2984654a5b8050ec0c0df69b8f081aa75e2/primitives/core/src/ecdsa.rs#L481).

This means that whatever message we are signing (in our case it's the `Commitment`) is going to be unconditionally `blake2_256` hashed before being signed.

Ideally for maximum Ethereum compatibility we would prefer this hash to be `keccak256` instead.

A solution is to either make the hasher somehow configurable in Substrate/`CryptoStore` or fall back to some other mechanism that will allow us to configure how the message is hashed before signing.

**Comment by tomusdrw** [comment]
We can introduce `ecsda_sign_prehashed` to `CryptoStore`, cause it already contain some crypto-specific methods.
@bkchr wdyt?

**Comment by bkchr** [comment]
You mean as host function and as function for the keystore?

Sounds reasonable to me 👍

**Comment by tomusdrw** [comment]
We don't even need a host function, this is purely client code, so it's just about adding to `LocalKeystore` and the trait.

**Comment by adoerr** [comment]
and impl `ecdsa::Pair::sign_prehash()`
